// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf6jaltgEap4enWgYekJtFYXzRJM3lgFI',
    appId: '1:522231016761:web:f3293cd1db1da2d4848ce8',
    messagingSenderId: '522231016761',
    projectId: 'suzy-flutter-app',
    authDomain: 'suzy-flutter-app.firebaseapp.com',
    storageBucket: 'suzy-flutter-app.firebasestorage.app',
    measurementId: 'G-QNM5XR56TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3ngKzlkzoO9VPDOdMnhnHmqhPs3pC1cQ',
    appId: '1:522231016761:android:ca7d59bb2c2cae2e848ce8',
    messagingSenderId: '522231016761',
    projectId: 'suzy-flutter-app',
    storageBucket: 'suzy-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTlgydWCL1psAhPLlnwZpUsqLNdcV8rwA',
    appId: '1:522231016761:ios:256ea6f56dfc0b9b848ce8',
    messagingSenderId: '522231016761',
    projectId: 'suzy-flutter-app',
    storageBucket: 'suzy-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.suzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTlgydWCL1psAhPLlnwZpUsqLNdcV8rwA',
    appId: '1:522231016761:ios:256ea6f56dfc0b9b848ce8',
    messagingSenderId: '522231016761',
    projectId: 'suzy-flutter-app',
    storageBucket: 'suzy-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.suzy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf6jaltgEap4enWgYekJtFYXzRJM3lgFI',
    appId: '1:522231016761:web:fa41cd16ae11815d848ce8',
    messagingSenderId: '522231016761',
    projectId: 'suzy-flutter-app',
    authDomain: 'suzy-flutter-app.firebaseapp.com',
    storageBucket: 'suzy-flutter-app.firebasestorage.app',
    measurementId: 'G-ENMY4VHFJW',
  );
}
